version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
- package-ecosystem: nuget
  directory: "/"
  groups:
    BenchmarkDotNet:
      patterns:
        - BenchmarkDotNet*
    polly:
      patterns:
        - Polly*
    xunit:
      patterns:
        - xunit*
  schedule:
    interval: weekly
    day: monday
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
